weblog/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern 
from .views import ArticleList, CategoryList, ArticleDetail

app_name = 'weblog'
urlpatterns = [
    path('',ArticleList.as_view(), name="home"), 
    path('page/<int:page>',ArticleList.as_view(),name="home"),
    path('article/<slug:slug>', ArticleDetail.as_view(), name="detail"),
    path('category/<slug:slug>', CategoryList.as_view(), name="category"),
    path('category/<slug:slug>/page/<int:page>',CategoryList.as_view(), name="category"),
]

account/models.py
from django.db import models

# Create your models here.

weblog/models.py
from django.db import models
from django.db.models.deletion import CASCADE, SET_NULL
from django.utils import timezone
from extensions.utils import jalali_convertor
from django.utils.html import format_html
from django.contrib.auth.models import User


#Managers
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)
# Create your models here.

class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=SET_NULL, related_name="childeren", verbose_name="زیر  گروه") #this is his own parent
    title = models.CharField(max_length=200,  verbose_name="عنوان")
    slug = models.SlugField(max_length=100, unique=True, verbose_name="آدرس مقاله")
    status = models.BooleanField(default=True, verbose_name="آیا نمایش داده شود؟")
    position = models.IntegerField(verbose_name="پوزیشن")
    
    class Meta:
        verbose_name = "دسته بندی" 
        verbose_name_plural = "دسته بندی ها"
        ordering = ['parent__id', 'position']     

    def __str__(self):
        return self.title
    
    objects = CategoryManager()
    



class Article(models.Model):
    STATUS_CHOICES = (
        ('d','پیش نویس'),
        ('p','منتشر شده')
    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name="articles", verbose_name="نویسنده")
    title = models.CharField(max_length=200, verbose_name="عنوان")
    slug = models.SlugField(max_length=100, unique=True, verbose_name="آدرس مقاله") 
    category = models.ManyToManyField(Category, verbose_name="دسته بندی", related_name="articles")
    description = models.TextField( verbose_name="توضیحات")
    thumbnail = models.ImageField(upload_to="images", verbose_name="تصویر")
    publish = models.DateTimeField(default=timezone.now, verbose_name="زمان انتشار")
    created = models.DateTimeField(auto_now_add=True)
    updatee = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name="وضعیت")

    def __str__(self):
        return self.title 

    def jpublish(self):
        return  jalali_convertor(self.publish)


    class Meta:
        verbose_name = "مقاله" 
        verbose_name_plural = "مقالات" 
        ordering=['-publish']
        
    jpublish.short_description = "زمان انتشار"


    def thumbnail_tag(self):
        return format_html("<img width=40 height=50 style='border-radius: 5px' src='{}'>".format(self.thumbnail.url))
    thumbnail_tag=short_description="تصویر مقاله"

    def category_published(self):
        return self.category.filter(status=True)
    
    objects= ArticleManager()


   

account/views.py
from django.shortcuts import render

# Create your views here.

weblog/views.py
from django.core.paginator import Paginator
from django.db.models.base import Model
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from .models import Article, Category
from django.views.generic import ListView, DetailView

# Create your views here.
# def home(request, page=1):
#     #we can connect to model and retrive data and send the result to themplate
#     ariticles_list = Article.objects.filter(status='p')
#     pagintor =  Paginator(ariticles_list,6)
#     # page=request.GET.get('page') ###we don't need to this code beacuse we pass the number of page as an argument and change the url
#     articles = pagintor.get_page(page)
#     context = { 
#         "articles": articles,
#         # "articles":Article.objects.all
#         # "articles": Article.objects.filter(status='p'),#.order_by('-publish'),
#         # "category": Category.objects.filter(status=True)
#     }
#     return render(request, "weblog/home.html", context)

##using listviews
class ArticleList(ListView):
    # model = Article    
    # template_name = "weblog/home.html"
    # context_object_name = "articles" 
    queryset =  Article.objects.published()
    paginate_by = 2
 
# def detail(request, slug):
#     context = {
#         "article":get_object_or_404(Article,slug=slug,status='p')
#     }
#     return render(request, "weblog/detail.html", context)  

##using deailview
class ArticleDetail(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Article, slug=slug, status='p')


# def category(reguest, slug, page=1):
#     category = get_object_or_404(Category,slug=slug,status=True)
#     articles_list = category.articles.published()
#     pagintor =  Paginator(articles_list,6)
#     articles = pagintor.get_page(page)
#     context={
#         "category": category,
#         "articles": articles
#     }
#     return render(reguest, "weblog/category.html", context)


##using Listview
class CategoryList(ListView):
    paginated = 5
    template_name = 'weblog/category_list.html'

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.articles.published()
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context

weblog/templates/weblog/article_detail.html
{% extends 'weblog/base.html' %}
{% block title%} | {{article.title}}{% endblock %}
{% load static %}
{% block main %}

<header class="masthead" style="background-image: url('{{article.thumbnail.url}}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>{{article.title}}</h1> 
                    <!-- <time>{{article.jpublish}}</time> -->
                </div>
            </div>
        </div>
    </div>
</header>


<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7 text-justify">
                {{article.description | linebreaks}}
            </div>
        </div>
    </div>
</article>
{% endblock %}

weblog/templates/weblog/article_list.html
{% extends 'weblog/base.html' %}
{% load static %}
{% block main %}

<header class="masthead" style="background-image: url('{% static "weblog/assets/img/home-bg.jpg" %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Django News</h1> 
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            {% for article in object_list %}
            <div class="post-preview">
                <a href="{% url 'weblog:detail' article.slug %}">
                    <h2 class="post-title">{{article.title}}</h2>
                    <h3 class="post-subtitle">{{article.description | truncatewords:20}}</h3>
                </a>
                <p class="post-meta">
                    نوشته شده توسط
                    <a href="#!">سعید</a>
                    {{article.jpublish}}
                </p>
                <div>
                    {% for cat in article.category_published.all %}
                        <a  href="{% url 'weblog:category' cat.slug %}">#{{cat.title}}</a>
                    {% endfor %}
                </div>
            </div> 
            {% endfor %}
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Pager-->
            {% if is_paginated %}
            <div class="clearfix page-botton">
                
                {% if page_obj.has_previous %}
                     <a class="btn btn-primary text-uppercase float-right " href="{% url 'weblog:home' page_obj.previous_page_number %}"> پست های جدید  &rarr;</a>
                {% endif %}

                
                {% if page_obj.has_next %}
                     <a class="btn btn-primary text-uppercase float-right " href="{% url 'weblog:home' page_obj.next_page_number %}" > پست های قدیمی  &larr;</a>
                {% endif %}
            </div> 
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

weblog/templates/weblog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Django News{% block title%}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static  'weblog/css/styles.css' %} " rel="stylesheet" />
        <link href="{% static  'weblog/css/rtl.css' %} " rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'weblog:home' %}">{% title %}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                {% category_navbar %}
            </div>
        </nav>
        <!-- Page Header-->

        <!-- Main Content-->
        {% block main %}
        {% endblock%}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static  'weblog/js/scripts.js' %} "></script>
    </body>
</html> 

weblog/templates/weblog/category.html
{% extends 'weblog/base.html' %}
{% load static %}
{% block main %}

<header class="masthead" style="background-image: url('{% static "weblog/assets/img/home-bg.jpg" %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Django News</h1> 
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <h3 class="alert alert-primary text-center"> دسته بندی : {{category.title}}</h3>
            <!-- Post preview-->
            {% for article in articles %}
            <div class="post-preview">
                <a href="{% url 'weblog:detail' article.slug %}">
                    <h2 class="post-title">{{article.title}}</h2>
                    <h3 class="post-subtitle">{{article.description | truncatewords:20}}</h3>
                </a>
                <p class="post-meta">
                    نوشته شده توسط
                    <a href="#!">سعید</a>
                    {{article.jpublish}}
                </p>
                <div>
                    {% for cat in article.category_published.all %}
                        <a href="#">#{{cat.title}}</a>
                    {% endfor %}
                </div>
            </div> 
            {% endfor %}
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Pager-->
            
            <div class="clearfix page-botton">
                
                {% if articles.has_previous %}
                     <a class="btn btn-primary text-uppercase float-right " href="{% url 'weblog:category' articles.previous_page_number %}"> پست های جدید  &rarr;</a>
                {% endif %}

                
                {% if articles.has_next %}
                     <a class="btn btn-primary text-uppercase float-right " href="{% url 'weblog:category' category.slug articles.next_page_number %}" > پست های قدیمی  &larr;</a>
                {% endif %}
            </div> 

        </div>
    </div>
</div>
{% endblock %}

weblog/templates/weblog/category_list.html
{% extends 'weblog/base.html' %}
{% load static %}
{% block main %}

<header class="masthead" style="background-image: url('{% static "weblog/assets/img/home-bg.jpg" %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Django News</h1> 
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <h3 class="alert alert-primary text-center"> دسته بندی : {{category.title}}</h3>
            <!-- Post preview-->
            {% for article in object_list %}
            <div class="post-preview">
                <a href="{% url 'weblog:detail' article.slug %}">
                    <h2 class="post-title">{{article.title}}</h2>
                    <h3 class="post-subtitle">{{article.description | truncatewords:20}}</h3>
                </a>
                <p class="post-meta">
                    نوشته شده توسط
                    <a href="#!">سعید</a>
                    {{article.jpublish}}
                </p>
                <div>
                    {% for cat in article.category_published.all %}
                        <a href="{% url 'weblog:category' cat.slug %}"">#{{cat.title}}</a>
                    {% endfor %}
                </div>
            </div> 
            {% endfor %}
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Pager-->
            
            <div class="clearfix page-botton">
                {% if is_paginated %}
                <div class="clearfix page-botton">
                    
                    {% if page_obj.has_previous %}
                         <a class="btn btn-primary text-uppercase float-right " href="{% url 'weblog:category' category.slugh page_obj.previous_page_number %}"> پست های جدید  &rarr;</a>
                    {% endif %}
    
                    
                    {% if page_obj.has_next %}
                         <a class="btn btn-primary text-uppercase float-right " href="{% url 'weblog:category' category.slugh page_obj.next_page_number %}" > پست های قدیمی  &larr;</a>
                    {% endif %}
                </div> 
                {% endif %}
            </div> 

        </div>
    </div>
</div>
{% endblock %}

weblog/templates/weblog/detail.html
{% extends 'weblog/base.html' %}
{% block title%} | {{article.title}}{% endblock %}
{% load static %}
{% block main %}

<header class="masthead" style="background-image: url('{{article.thumbnail.url}}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>{{article.title}}</h1> 
                    <!-- <time>{{article.jpublish}}</time> -->
                </div>
            </div>
        </div>
    </div>
</header>


<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7 text-justify">
                {{article.description | linebreaks}}
            </div>
        </div>
    </div>
</article>
{% endblock %}

weblog/templates/weblog/home.html
{% extends 'weblog/base.html' %}
{% load static %}
{% block main %}

<header class="masthead" style="background-image: url('{% static "weblog/assets/img/home-bg.jpg" %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Django News</h1> 
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            {% for article in articles %}
            <div class="post-preview">
                <a href="{% url 'weblog:detail' article.slug %}">
                    <h2 class="post-title">{{article.title}}</h2>
                    <h3 class="post-subtitle">{{article.description | truncatewords:20}}</h3>
                </a>
                <p class="post-meta">
                    نوشته شده توسط
                    <a href="#!">سعید</a>
                    {{article.jpublish}}
                </p>
                <div>
                    {% for cat in article.category_published.all %}
                        <a  href="{% url 'weblog:category' cat.slug %}">#{{cat.title}}</a>
                    {% endfor %}
                </div>
            </div> 
            {% endfor %}
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Pager-->
            <div class="clearfix page-botton">
                
                {% if articles.has_previous %}
                     <a class="btn btn-primary text-uppercase float-right " href="{% url 'weblog:home' articles.previous_page_number %}"> پست های جدید  &rarr;</a>
                {% endif %}

                
                {% if articles.has_next %}
                     <a class="btn btn-primary text-uppercase float-right " href="{% url 'weblog:home' articles.next_page_number %}" > پست های قدیمی  &larr;</a>
                {% endif %}
            </div> 

        </div>
    </div>
</div>
{% endblock %}

weblog/templates/weblog/partials/category_loop.html
<ul class="navbar-nav ms-auto py-4 py-lg-0">
    {% for cat in cat.children.active %}
    <li class="nav-item">
        <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'weblog:category' cat.slug %}">{{cat.title}}</a>
        {% if cat.children.active %}
           {% include 'weblog/partial/category_loop.html' %}
        {% endif %}     
    </li>
    </li>
    {% endfor %}
</ul>  

weblog/templates/weblog/partials/category_navbar.html
<div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ms-auto py-4 py-lg-0">
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'weblog:home' %}">خانه</a></li>
        {% for cat in category %} 
            {% if cat.parent == None %}
            <li class="nav-item">
                <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'weblog:category' cat.slug %}">{{cat.title}}</a></li>
                {% if cat.children.active %}
                    {% include 'weblog/partial/category_loop.html' %}
                {% endif %}
            {% endif %}
        {% endfor %}
    </ul>
</div>